#!/bin/sh

# shellcheck disable=SC3001 # process substitution are defined in alpine's /bin/sh

this_script="$( readlink -f "${0}" )"
this_dir="${this_script%/*}"

dir_has_no_files () {
  dhnf_directory="${1}"

  # count files in directory
  dhnf_filecount="$( 
    find "${dhnf_directory}" -type f -mindepth 1 -maxdepth 1 \
    | wc -l
  )"

  # true if empty
  test "${dhnf_filecount}" -eq "0"
}

dir_to_unit () {
  dtu_dirname="${1}"

  case "${dtu_dirname}" in
    # truncated "daily"
    dai) 
      echo "day"
      ;;
    
    # truncated "annually"
    annual) 
      echo "year"
      ;;

    *)
      echo "${dtu_dirname}" 
      ;;
  esac
}

# check *ly dirs in "/kiwi-cron" directory
schedule_dirs="$( 
  find "/kiwi-cron" -type d -name "*ly" -mindepth 1 -maxdepth 1
)"

for schedule_dir in ${schedule_dirs}; do
  # ignore dirs without files
  if dir_has_no_files "${schedule_dir}"; then
    continue
  fi

  # infer units by directory name
  dir_name="${schedule_dir##*/}"
  units="${dir_name%ly}"
  units="$( dir_to_unit "${units}" )"

  "${this_dir}/create_schedule" \
    "1" "${units}" "run-parts '${schedule_dir}'" \
    | "${this_dir}/randomize_schedule"
done

# check dirs in "/kiwi-cron/every" directory
every_schedule_dirs="$( 
  find "/kiwi-cron/every" -type d -mindepth 1 -maxdepth 1
)"

for schedule_dir in ${every_schedule_dirs}; do
  # ignore dirs without files
  if dir_has_no_files "${schedule_dir}"; then
    continue
  fi

  # infer schedule params by directory name
  dir_name="${schedule_dir##*/}"
  case "${dir_name}" in
    *_*) # looks like: every/5_minutes
      read -r every units < \
        <( echo "${dir_name}" | tr '_' ' ' )
      ;;

    *) # probably looks like: every/day
      every="1"
      units="${dir_name}"
      ;;
  esac

  # remove trailing "s" if present
  units="${units%s}"

  "${this_dir}/create_schedule" \
    "${every}" "${units}" "run-parts '${schedule_dir}'" \
    | "${this_dir}/randomize_schedule"
done
